version: '3.3'

services:

  frontend:
    image: ploneorgbr/site-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    depends_on:
      - backend
    networks:
      - public
      - plonebr
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # SERVICE
        - traefik.http.services.plonebr-frontend.loadbalancer.server.port=3000
        # HOSTS: Main
        - traefik.http.routers.plonebr-frontend.rule=Host(`plone.org.br`)
        - traefik.http.routers.plonebr-frontend.entrypoints=https
        - traefik.http.routers.plonebr-frontend.tls=true
        - traefik.http.routers.plonebr-frontend.tls.certresolver=le
        - traefik.http.routers.plonebr-frontend.service=plonebr-frontend
        - traefik.http.routers.plonebr-frontend.middlewares=gzip

  backend:
    image: ploneorgbr/site-backend:latest
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}'"
    networks:
      - public
      - plonebr
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.plonebr-backend.loadbalancer.server.port=8080
        # Middlewares
        - traefik.http.middlewares.plonebr-backend.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)
        - traefik.http.middlewares.plonebr-backend.replacepathregex.replacement=/VirtualHostBase/https/plone.org.br/Plone/++api++/VirtualHostRoot/$$1
        # Router
        - traefik.http.routers.plonebr-backend.rule=Host(`plone.org.br`) && PathPrefix(`/++api++`)
        - traefik.http.routers.plonebr-backend.entrypoints=https
        - traefik.http.routers.plonebr-backend.tls=true
        - traefik.http.routers.plonebr-backend.service=plonebr-backend
        - traefik.http.routers.plonebr-backend.middlewares=gzip,plonebr-backend

networks:
  public:
    external: true
    driver: overlay
  plonebr:
    driver: overlay
